# Generated by Django 2.0.2 on 2018-03-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchaseorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
