# Generated by Django 2.0.2 on 2018-03-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180322_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='product',
            new_name='product_type',
        ),
    ]
