# Generated by Django 2.0.2 on 2018-03-23 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_buyreciept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyReciept',
            new_name='BuyReceipt',
        ),
    ]
