# Generated by Django 2.0.2 on 2018-03-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180322_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyreceipt',
            name='cc_num',
            field=models.PositiveIntegerField(default=1234567812345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyreceipt',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
