# Generated by Django 2.0.2 on 2018-03-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180322_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='product_type',
            new_name='title',
        ),
    ]
