# Generated by Django 2.0.2 on 2018-03-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180322_2308'),
        ('shop', '0007_product_image'),
    ]

    operations = [
    ]
